name: ⚙️

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality:
    name: 🦀 Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 📦 Install Tauri system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: 📦 Setup mise
        id: setup-mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          experimental: true

      - name: ♻️ Manage Rust toolchains Cache
        id: cache-rust
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: |
            ~/.rustup/toolchains/
            ~/.cargo/
            target/
          key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            rust-${{ runner.os }}-

      # HACK: based on https://github.com/jdx/mise-action/issues/215
      - name: ⚙️ Force Reinstall Rust Toolchains on Cache Miss
        if: ${{ steps.setup-mise.outputs.cache-hit == 'true' && steps.cache-rust.outputs.cache-hit != 'true' }}
        run: mise install --force rust

      - name: ✅ Run CI Checks
        run: mise run ci-check
